name: Node CI

on: pull_request

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: lint
        run: |
          yarn
          yarn lint
        
  test:

    runs-on: ${{ matrix.os }}
    env:
      DISPLAY: :99.0

    strategy:
      matrix:
        node-version: [12.x]
        os: [ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install xvfb
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt update
        sudo apt install -y xvfb graphicsmagick
        npm install -g xvfb-maybe
        Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
    - name: yarn install
      run: yarn
    - name: yarn unit
      run: yarn unit
    - name: yarn e2e
      run: yarn e2e
    - name: Upload screenshots
      if: failure()
      uses: actions/upload-artifact@v1.0.0
      with:
        # Artifact name
        name: ${{ matrix.os }}-screenshots
        # Directory containing files to upload
        path: screenshots
